### ISSUE TITLE
TAGS Explorer display not working

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#10]
The buttons don't seem to work-no "switching" occurs. The feature worked last night during our conversation. I'm on a different computer now, but I'm not sure that should make a difference.

**Comment by woodwardtw** [comment]
I turned all that stuff off to see if it was the cause of the issue with the slider that Alan mentioned. It doesn't appear to be. Once I get that addressed I'll turn it back on and resolve the issue.

**Comment by woodwardtw** [comment]
Should be functional now and slider appears functional across a spectrum of browsers. Please re-open if you see otherwise (you will likely need to purge your cache).
