### ISSUE TITLE
How do I edit the documentation wiki?

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#12]
For example, it appears that the category used for putting posts in the slider is "front marquee," not "slider." I'm happy to make the change but I don't see how to edit the wiki.

**Comment by cogdog** [comment]
Sorry, I had changed it. As owner of the repo, Tom can add you as a collaborator so you can edit the wiki.

**Comment by woodwardtw** [comment]
Gardner should now see an invite to be a full member. Sorry about that.
