### ISSUE TITLE
Category for slider posts

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#13]
Could we please change the category for posts on the slider back to "slider"? I think it's better to align what the theme calls an area with the category name we use to put content in that area, wherever that seems reasonable. "Featured" isn't a problem--I don't think we should call the category "left header" or whatever. But why not keep "slider" consistent, just as it is in the current documentation?

I'm thinking ahead to when I'm no longer a hub director and I hand the keys over to someone else.

**Comment by woodwardtw** [comment]
Updating now.

**Comment by cogdog** [comment]
FYI, the reason I changed it is because it shows up as a category name on the site (see the footer). If I was a participant I might not know what "Slider" means. That's all. Not worth chewing on.
