### ISSUE TITLE
Upgraded to WP 4.7

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#15]
No issues noted. Just FYI.

**Comment by woodwardtw** [comment]
Glad it worked out. 

I was considering doing that but I killed the ALT Lab site for a bit and so I decided I'd upgraded enough things today.

**Comment by GardnerCampbell** [comment]
+1

**Comment by cogdog** [comment]
I just applied this fix to another site

https://wordpress.org/support/topic/broken-with-the-wordpress-4-7-update/#post-8525319

It cleared the FWP error, but not sure if there is any other side effects (it's a site that only lightly uses FWP). The developer might respond to this sometime in late April with his track record.
