### ISSUE TITLE
Default excerpt syndicated in, now post won't syndicate

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#16]
User Jodi Fisler at jodifisler.wordpress.com successfully added her feed to the hub, but the post that syndicated in looks to be a default "excerpt" post. Jodi has now written a post, and the syndicated post LINK leads to that post, but I can't get that post--the one she actually wrote--to syndicate in. The default excerpt keeps appearing. I've tried unsubscribing and resubscribing feed but no joy.

**Comment by woodwardtw** [comment]
I think we’re good to go. In scenarios like this, I erase/resyndicate the individual post and then update the feed.

**Comment by woodwardtw** [comment]
Not fixed?

**Comment by GardnerCampbell** [comment]
Well, I wish--but maybe not so much? I erased and resyndicated the post. I updated the feed. The problem seems to persist. In this case, the post appears via syndication but doesn't display unless it's in a "group" category. Also, when I go in and manually put the category on the post, the excerpt is what appeared again. I'll give it another shot now, but I'm guessing the same thing will happen.

**Comment by woodwardtw** [comment]
I see her post from the front page after selecting OTHER AAC&U GROUP under Recently Opened. I believe that text is correct (not default). 

Where do you want to see it?

**Comment by woodwardtw** [comment]
Never mind anything I've said. Give me two seconds.

**Comment by GardnerCampbell** [comment]
You see the correct post when you go to her blog, but it doesn't display that way. Jodi's in the Virginia group, so I categorized her post that way, and then the excerpt appeared again. Are we having fun yet. :)

**Comment by GardnerCampbell** [comment]
Ah--two seconds gratefully granted.

**Comment by woodwardtw** [comment]
With you now. Added the VA element to the feed via FWP . . . maybe she didn't choose it when signing up but should apply going forward.

The excerpt issue is on her end in that the excerpt is manually set and remains the default text. You can see that in the pure RSS feed from her end [https://jodifisler.wordpress.com/feed/](https://jodifisler.wordpress.com/feed/)

**Comment by GardnerCampbell** [comment]
Ah, thanks. I can communicate that to her. I had checked the feed but not carefully. I need to get my passport verified for Programistan. Just need to go there! Always heard the beaches were great.

THANKS.

**Comment by woodwardtw** [comment]
It was a slightly odd scenario. I don't recall WP setting default excerpt language previously but I'm getting old. 

Looking at the form entry, she did choose course affiliation 6 (va group). 

I manually set it by going http://openlearninghub.net/wp-admin/admin.php?page=feedwordpress%2Fsyndication.php and then choosing the category element under the feed. 

I'll try to see if this was a blip or if something isn't quite working.

**Comment by GardnerCampbell** [comment]
Yep. Odd scenario indeed. Thx for shooting my troubles. 

(from mobile)
