### ISSUE TITLE
Funky usernames

### ISSUE THREAD

**Issue by cogdog** [woodwardtw/openlearninghub#19]
My scripts create a username based on what they enter in the signup for twitter names. Invariably people enter URLs or other odd things. I could probably do better with the error checking.

Anyhow it causes their names to be represented funny on the site since it expects @______ e.g. this dude

![wilson](https://cloud.githubusercontent.com/assets/463038/22111357/4c334e36-de1c-11e6-90eb-24e963ec01c3.jpg)

The fix is to edit the user; I have a plugin that lets you change the username (usually you cannot) with the button next to the field, so I made him just `MCorbettWIlson` 

Then I enter `@MCorbettWIlson` for a nickname, and wilson is all set to go

![wilson2](https://cloud.githubusercontent.com/assets/463038/22111444/8b592054-de1c-11e6-8aa2-54132fceba92.jpg)

Each time I do this I forget how many tiny things need some tweaking.

**Comment by GardnerCampbell** [comment]
Thanks, Alan--it's great for me to learn these things, too. The plugin
looks like a great addition.

**Comment by cogdog** [comment]
Doh, this really belongs in the wiki docs. Done https://github.com/woodwardtw/openlearninghub/wiki/Fixing-User-Names
