### ISSUE TITLE
Feed issues

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#24]
Meg Mulrooney's category feed returns this error:

Diagnostic information

HTTP request failure

cURL error 28: connect() timed out!
HTTP Transport:

string(12) "WP_Http_Curl"

The feed URL does return an XML feed, however: http://mmulrooney.net/category/liberal-education/feed/. Perhaps a case for Feedburner.

This URL was entered incorrectly, so far as I can tell, and caused an XML error:

https://rrdaniel2-open-learning.blog/

I've unsubcribed and resubscribed. Seems to be working now.

**Comment by GardnerCampbell** [comment]
Update: rrdaniel2 category should be syndicated and open participants. I think I've set that up correctly, but I discovered the setting must precede the update, as it doesn't retroactively categorize already syndicated posts. Makes sense.

**Comment by cogdog** [comment]
The Curl error was something I've only seen in the last few years. It happened with your blog, and also recently with Todd Conaway's both hosted at Blue Host. My guess/hunch is that they block these requests (you may know, but cURL is a unix command to fetch the contents from a remote URL), and the only fix I have seen is the FeedBurner washing.

It's very common that people enter the same URL for the feed and the site. I need to put an error check for that. I just wish people would use the "help me" option, it's a lot less hassle. 

There is a nice FWP option that works well, from the list of feeds, find the problem one, and click "Change Feed" -- it allows you to enter the correct one-- I always figure out the direct URL for the feed.

And yes, any change you make for the feed as far as categories only affects new content.

And last;y, a small thing about manually adding feeds. When you check the "Virginia" or other subcategory for the affiliation in the Feed -> Category settings, I found sometimes FWP does not include the parent category ("Syndicated") in its data. It might be assuming that it's a child category wordpress knows the parent by default. This does not affect syndication, but will cause the blog not to be listed on the all blogs listing.

If you want to get down and dirty with the details, go to Links, find the feed, and look way down t the long scroll of "notes" -- its where FWP stores its data. The categories should be listed like:

`cats: {category#4}\n{category#7}\n{category#4}\n{category#7}`

They are repeated which is not a problem, but it needs at least one the `{category#4\n' in the mix (7 is the sub category)

Both of the feeds you listed are ok on this front, I thought I saw in setup where it was not always added, but never figured out the where/why.

**Comment by GardnerCampbell** [comment]
Thanks. Meg M's feed is washed and working. I knew the change feed trick but it's great to know more about down and dirty details. THX.
