### ISSUE TITLE
Miss Toms.js

### ISSUE THREAD

**Issue by cogdog** [woodwardtw/openlearninghub#7]
Getting not found for
http://openlearninghub.net/wp-content/themes/openlearninghubfunctions/js/toms-extras.js?ver=1.0

Not sure if that error is causing the slider not to load (?)

**Comment by cogdog** [comment]
Fixed, there was a missing slash before 'functions'

Slider still not displaying. it's in the source...

**Comment by woodwardtw** [comment]
I think I've removed both the function and the js and the slider is still down. I'll get back to this in a few hours.

**Comment by cogdog** [comment]
There is something in the slider javascript that is not changing the visibility of the .slide class; I hacked the the CSS at least to make it show. Not sure impact. This did happen long ago on TV, cannot remember what it was.

hacked styles.css on server

````
/* #slides .slides_container .slide { display: none; overflow: hidden; } */

#slides .slides_container .slide { overflow: hidden; }

````

**Comment by woodwardtw** [comment]
I believe the TAGS stuff is now fully replaced and the stuff remains up. Really puzzled in general about this though. Going to close it as functional.

**Comment by cogdog** [comment]
My new hunch it is a conflict with the library it uses for the slides http://slidesjs.com/ stores in includes/js/slides.min.jquery.js being old and conflicting with current version of jQuery WP uses- not sure if the cycle plugin is used /js/jquery.cycle.all.min.js 

Could try replacing ones in the theme with newer ones. On the other hand, if my CSS hack works, leave it?? I think the slides are hidden until the images are loaded.

**Comment by woodwardtw** [comment]
My vote is to leave it be. I'd let that sleeping dog lie.
