### ISSUE TITLE
Feed Wordpress Activated

### ISSUE THREAD

**Issue by cogdog** [woodwardtw/openlearninghub#8]
feeds now checked hourlut- For gardner's info, it's FWP settings -> Feeds & Updates

http://openlearninghub.net/wp-admin/admin.php?page=feedwordpress%2Ffeeds-page.php

Set Update Scheduling menu for `automatically check for updates after page loads`

**Comment by GardnerCampbell** [comment]
Got it. Basic FWP stuff like this is known to me. Just FYI.

**Comment by GardnerCampbell** [comment]
We can probably close this one now.

**Comment by GardnerCampbell** [comment]
Oh, I'm a made man, so I can do this now! Cool.
