### ISSUE TITLE
Going back beyond first page of posts?

### ISSUE THREAD

**Issue by GardnerCampbell** [woodwardtw/openlearninghub#9]
Is there a way to see earlier posts after they fall off the front page?

**Comment by cogdog** [comment]
Yes,  the category views listed in the menu

![menu](https://cloud.githubusercontent.com/assets/463038/20840999/7147dbba-b86f-11e6-856f-370e7cd6a341.jpg)

**Comment by cogdog** [comment]
Okay, I added a button to the bottom of the recent news display on front page-- if there are more 10 posts in the category, it links to page 2 of the category archive... e.g.

![more-news-button](https://cloud.githubusercontent.com/assets/463038/20856749/4a274dd0-b8d4-11e6-886e-b315856c5f8b.jpg)


Does that work?

**Comment by GardnerCampbell** [comment]
Yes, that's fine. Thanks. My goal is to have easy access to earlier posts no matter what category of posts is showing on the front page. It looks like that;s where we are. Thanks.
